name: Update CHANGELOG with LLM Agent

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate changelog content
        id: llm
        run: |
          echo "## Changelog" > new-changelog.md
          echo "" >> new-changelog.md
          echo "- Placeholder: AI agent would generate changelog here." >> new-changelog.md

      - name: Create changelog pull request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: update CHANGELOG.md with latest changes"
          title: "Automated CHANGELOG update"
          body: "This pull request was created automatically by the LLM Agent workflow."
          branch: changelog-update
          delete-branch: true
          add-paths: |
            CHANGELOG.md
